#!/usr/bin/env bash
## Creates the file /var/run/myscript.pid containing its PID
##
## Displays "To infinity and beyond" indefinitely
##
## Displays "I hate the kill command" when receiving a SIGTERM signal
##
## Displays "Y U no love me?!" when receiving a SIGINT signal
##
## Deletes the file /var/run/myscript.pid and terminates itself
## when receiving a SIGQUIT or SIGTERM signal

handel(){
	rm -f /var/run/myscript.pid
	exit
}

if [ ! -e /var/run/myscript.pid ]; then
	echo "$$" > /var/run/myscript.pid
fi


trap "echo 'I hate the kill command' && handel" SIGTERM
trap "handel" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT

while true;
do
	echo "To infinity and beyond"
	sleep 2
done

