#!/usr/bin/env bash
## script that print to stdout from 1 to 20 and have some print between
i=0

while [ $i -lt 20 ]
do
	((i++))
	echo "$i"
	case "$i" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
		echo "bad luck from Italy"
esac
done
