#!/usr/bin/env bash
## Write a Bash script that gives you information about the school file
file_name="school"

if [ -e "$file_name" ]; then
	echo "$file_name file exists"
	if [ "$(file $file_name | cut -d ":" -f "2")" = " empty" ]; then
		echo "$file_name file is empty"
	else
		echo "$file_name file is not empty"
	fi
	if [ -f "$file_name" ]; then
		echo "$file_name is a regular file"
	fi
else
	echo "$file_name file does not exist"
fi
	

